name = "client"
version = "1.0.0"
target = "javascript"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_json = ">= 3.1.0 and < 4.0.0"
lustre = ">= 5.5.2 and < 6.0.0"
plinth = ">= 0.7.0 and < 1.0.0"
shared = { path = "../shared" }
gleam_fetch = ">= 1.3.0 and < 2.0.0"
gleam_http = ">= 4.3.0 and < 5.0.0"
rsvp = ">= 1.2.0 and < 2.0.0"
modem = ">= 2.0.0 and < 3.0.0"

[dev-dependencies]
lustre_dev_tools = ">= 2.0.0 and < 3.0.0"

[tools.lustre.dev]
proxy = { from = "/api", to = "http://localhost:8080/api" }

[tools.lustre.build]
outdir = "../server/priv/static"
